import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { getFraudAlerts } from '../api/fraudAlertApi';
import type { FraudAlert } from '../types/common.types';
import styles from './AlertsPage.module.css';

function RiskBadge({ level }: { level: string }) {
  const cls =
    level === 'HIGH' ? styles.alertBadgeHigh :
    level === 'MEDIUM' ? styles.alertBadgeMedium :
    styles.alertBadgeLow;
  return <span className={`${styles.alertBadge} ${cls}`}>● {level}</span>;
}

export default function AlertsPage() {
  const [page, setPage] = useState(1);
  const pageSize = 15;

  const { data, isLoading } = useQuery({
    queryKey: ['fraudAlerts', page],
    queryFn: () => getFraudAlerts(page, pageSize),
  });

  const alerts = data?.items ?? [];
  const totalPages = data?.totalPages ?? 1;

  return (
    <>
      <div className={styles.alertBanner}>
        <div className={styles.alertBannerInner}>
          <div>
            <h1 className={styles.alertTitle}>Fraud Alerts</h1>
            <p className={styles.alertSubtext}>Alerts generated by the fraud detection system</p>
          </div>
          <div className={styles.alertBannerStats}>
            <span className={styles.alertBannerStat}>{data?.totalRecords ?? 0} total alerts</span>
          </div>
        </div>
      </div>

      <div className={styles.alertBody}>
        <div className={styles.alertCard}>
          <div className={styles.alertCardHeader}>
            <h3 className={styles.alertCardTitle}>All Alerts</h3>
            <span className={styles.alertCardCount}>{data?.totalRecords ?? 0} records</span>
          </div>

          {isLoading ? (
            <div className={styles.alertLoading}>
              <div className={styles.alertSpinner} />
              Loading...
            </div>
          ) : alerts.length === 0 ? (
            <div className={styles.alertEmpty}>
              <span className={styles.alertEmptyIcon}>🚨</span>
              No fraud alerts found
            </div>
          ) : (
            <table className={styles.alertTable}>
              <thead>
                <tr>
                  <th>Alert ID</th>
                  <th>Transaction ID</th>
                  <th>Risk Level</th>
                  <th>Reason</th>
                  <th>Date</th>
                </tr>
              </thead>
              <tbody>
                {alerts.map((a: FraudAlert) => (
                  <tr key={a.fraudAlertId}>
                    <td className={styles.alertIdCell}>#{a.fraudAlertId}</td>
                    <td className={styles.alertIdCell}>#{a.transactionId}</td>
                    <td><RiskBadge level={a.riskLevel} /></td>
                    <td className={styles.alertReasonCell}>{a.reason}</td>
                    <td>{new Date(a.createdAt).toLocaleDateString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}

          {totalPages > 1 && (
            <div className={styles.alertPagination}>
              <button
                className={styles.alertPageBtn}
                onClick={() => setPage((p) => Math.max(1, p - 1))}
                disabled={page === 1}
              >
                ← Prev
              </button>
              <span className={styles.alertPageInfo}>Page {page} of {totalPages}</span>
              <button
                className={styles.alertPageBtn}
                onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                disabled={page === totalPages}
              >
                Next →
              </button>
            </div>
          )}
        </div>
      </div>
    </>
  );
}
